import './globals.css';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

const pretendard = localFont({
  src: [
    {
      path: "./fonts/Pretendard-Regular.woff",
      weight: "400",
      style: "regular",
    },
    {
      path: "./fonts/Pretendard-Medium.woff",
      weight: "600",
      style: "medium",
    },
    {
      path: "./fonts/Pretendard-Bold.woff",
      weight: "700",
      style: "bold",
    },
  ],
  // Expose a CSS variable for Tailwind integration
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable}`}>{children}</body>
    </html>
  );
}
